#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LogicReinc.Android.Resource", IsApplication=false)]

namespace LogicReinc.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int binding = 2130771968;
			
			// aapt resource value: 0x7f010002
			public static int bindvalue = 2130771970;
			
			// aapt resource value: 0x7f010003
			public static int onclick = 2130771971;
			
			// aapt resource value: 0x7f010001
			public static int visibility_binding = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020001
			public static int ApplicationName = 2130837505;
			
			// aapt resource value: 0x7f020000
			public static int Hello = 2130837504;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] BoundButton = new int[] {
					2130771971};
			
			// aapt resource value: 0
			public static int BoundButton_onclick = 0;
			
			public static int[] BoundConditional = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public static int BoundConditional_bindvalue = 0;
			
			public static int[] BoundItem = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public static int BoundItem_binding = 0;
			
			// aapt resource value: 1
			public static int BoundItem_visibility_binding = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
