#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LogicReinc.Android.TestApp.Resource", IsApplication=true)]

namespace LogicReinc.Android.TestApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::LogicReinc.Android.Resource.Attribute.binding = global::LogicReinc.Android.TestApp.Resource.Attribute.binding;
			global::LogicReinc.Android.Resource.Attribute.bindvalue = global::LogicReinc.Android.TestApp.Resource.Attribute.bindvalue;
			global::LogicReinc.Android.Resource.Attribute.onclick = global::LogicReinc.Android.TestApp.Resource.Attribute.onclick;
			global::LogicReinc.Android.Resource.Attribute.visibility_binding = global::LogicReinc.Android.TestApp.Resource.Attribute.visibility_binding;
			global::LogicReinc.Android.Resource.String.ApplicationName = global::LogicReinc.Android.TestApp.Resource.String.ApplicationName;
			global::LogicReinc.Android.Resource.String.Hello = global::LogicReinc.Android.TestApp.Resource.String.Hello;
			global::LogicReinc.Android.Resource.Styleable.BoundButton = global::LogicReinc.Android.TestApp.Resource.Styleable.BoundButton;
			global::LogicReinc.Android.Resource.Styleable.BoundButton_onclick = global::LogicReinc.Android.TestApp.Resource.Styleable.BoundButton_onclick;
			global::LogicReinc.Android.Resource.Styleable.BoundConditional = global::LogicReinc.Android.TestApp.Resource.Styleable.BoundConditional;
			global::LogicReinc.Android.Resource.Styleable.BoundConditional_bindvalue = global::LogicReinc.Android.TestApp.Resource.Styleable.BoundConditional_bindvalue;
			global::LogicReinc.Android.Resource.Styleable.BoundItem = global::LogicReinc.Android.TestApp.Resource.Styleable.BoundItem;
			global::LogicReinc.Android.Resource.Styleable.BoundItem_binding = global::LogicReinc.Android.TestApp.Resource.Styleable.BoundItem_binding;
			global::LogicReinc.Android.Resource.Styleable.BoundItem_visibility_binding = global::LogicReinc.Android.TestApp.Resource.Styleable.BoundItem_visibility_binding;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int binding = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int bindvalue = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int onclick = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int visibility_binding = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int root = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int TestView = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] BoundButton = new int[] {
					2130771971};
			
			// aapt resource value: 0
			public const int BoundButton_onclick = 0;
			
			public static int[] BoundConditional = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int BoundConditional_bindvalue = 0;
			
			public static int[] BoundItem = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int BoundItem_binding = 0;
			
			// aapt resource value: 1
			public const int BoundItem_visibility_binding = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
